### ISSUE TITLE
struct.error: argument out of range

### ISSUE THREAD

**Issue by MarkLTZ** [Freakboy/vnc2flv#1]
Hello, I have the following error on Centos8:

```
[mark@localhost ~]$ /usr/local/bin/flvrec.py -P ~/.vnc/password -C 1920x1080+0-0 -r 5 -o /tmp/vnc.flv :1
start recording
Traceback (most recent call last):
  File "/usr/local/bin/flvrec.py", line 125, in <module>
    if __name__ == "__main__": sys.exit(main(sys.argv))
  File "/usr/local/bin/flvrec.py", line 123, in main
    debug=debug, verbose=verbose)
  File "/usr/local/bin/flvrec.py", line 51, in flvrec
    client.idle()
  File "/usr/local/lib64/python3.6/site-packages/vnc2flv/rfb.py", line 493, in idle
    self.feed(data)
  File "/usr/local/lib64/python3.6/site-packages/vnc2flv/rfb.py", line 107, in feed
    (self._length, self._state) = self._state(x)
  File "/usr/local/lib64/python3.6/site-packages/vnc2flv/rfb.py", line 257, in start_2
    return self.loop()
  File "/usr/local/lib64/python3.6/site-packages/vnc2flv/rfb.py", line 260, in loop
    self.request_update()
  File "/usr/local/lib64/python3.6/site-packages/vnc2flv/rfb.py", line 91, in request_update
    self.send(b'\x03\x01' + pack('>HHHH', *self.clipping))
struct.error: argument out of range

```
Could you help me to solve it?

**Comment by MarkLTZ** [comment]
Solved with the following workaround:

```
diff --git a/vnc2flv/rfb.py b/vnc2flv/rfb.py
index 1cf8125..ff6b644 100644
--- a/vnc2flv/rfb.py
+++ b/vnc2flv/rfb.py
@@ -88,7 +88,7 @@ class RFBProxy(object):
         if not self.session_open: return
         if self.debug:
             print('FrameBufferUpdateRequest', file=sys.stderr)
-        self.send(b'\x03\x01' + pack('>HHHH', *self.clipping))
+        self.send(b'\x03\x01' + pack('>hhhh', *self.clipping))
         return
 
     def open(self):

```

Could you check it please?
Thanks

**Comment by Freakboy** [comment]
> Solved with the following workaround:
> 
> ```
> diff --git a/vnc2flv/rfb.py b/vnc2flv/rfb.py
> index 1cf8125..ff6b644 100644
> --- a/vnc2flv/rfb.py
> +++ b/vnc2flv/rfb.py
> @@ -88,7 +88,7 @@ class RFBProxy(object):
>          if not self.session_open: return
>          if self.debug:
>              print('FrameBufferUpdateRequest', file=sys.stderr)
> -        self.send(b'\x03\x01' + pack('>HHHH', *self.clipping))
> +        self.send(b'\x03\x01' + pack('>hhhh', *self.clipping))
>          return
>  
>      def open(self):
> ```
> 
> Could you check it please?
> Thanks

I guess it's because of different systems, official Python doc has instructions.
![image](https://user-images.githubusercontent.com/17876931/75519291-dae27300-5a3d-11ea-9bae-9107c52b161a.png)

**Comment by MarkLTZ** [comment]
Hellp Freakboy,

I solved this issue. It happen when I run for error flcrec.py passing wrong y value as geometry:

`flvrec.py -d -P ~/.vnc/password -C 1920x1080+0-0 -r 30 -o /tmp/vnc.flv :1`

is must be:

`flvrec.py -d -P ~/.vnc/password -C 1920x1080+0+0 -r 30 -o /tmp/vnc.flv :1`
